sudo: required
language: node_js
node_js:
- "8"
services:
- docker
before_script:
- scripts/set_version.sh
script:
- npm run-script lint
- npm run-script build
- npm test
- docker build -t btburnett3/couchbase-index-manager:${TRAVIS_BUILD_NUMBER} .
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/docker_push.sh
  on:
    tags: true
- provider: npm
  skip_cleanup: true
  email: bburnett@centeredgesoftware.com
  api_key:
    secure: "iHbO0V1u/3IvY4LhJCwHj+FmLolLYXSxr06+tIn+cMxDMYBATyu5PnQbpT2cWFg0hLXpN9SBw4L1XSy5z0tW9fX32i5ThqHT2j52tOzVVKgq8CA6KudT1YAHjz+5P5Dt1HCXNKf8jFPGZtCItMzQAIh8p5+7eke8yld1X3uTXVl+nYsa2BaYG1I1pM43a+w6ska7Qh64g9FzncQCclWXe88GQMgDUvDVgXU81TfQsxAy3pe9kBKWerVWd3RW8qrq3h3ph7XGs2mZj8c1m7fGAMWxCJ5Kboeuh7N+hdT15PKeMmsbXiLpKk456bsZjs9yAXPrIEUKfHnR9fCM1NzcsKtjAIfy0shs2bTNctRDgkB6VEm3rWJh8VtBDSBpuOHP2EBzYR0A+/puRNl5lEhyapYWfAGm9KeEIHF3gMas35QWTrFTbxPu7//2rSp6cDCCia6qtG6sz1IJhQObabh12S119PVkU6QsCvHv7DPGYGMTW+FithgqQFxlqSUYe7v3LM0/57NUF9YAtzqxfKOQrKAeZ4mR4qTUdbZA1rVGb/aUZjqdnV0QHmUAZE/mcwEehN9vj64bfW31SXclAXvFL0xlRSmBJNfqFnvn6n1QyRNOufR1wd9a8o0ewAQZCX+dnHsCJgBtYkK5ap06BcJ2ec+H1L0PiWoeB9xwfvbYpog="
  on:
    tags: true
cache:
  directories:
  - node_modules
