sudo: required
language: node_js
node_js:
- "16"
services:
- docker
before_script:
- scripts/set_version.sh
script:
- npm run build
- npm run lint
- npm test
- docker build -t btburnett3/couchbase-index-manager:${TRAVIS_BUILD_NUMBER} .
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/docker_push.sh
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: cd packages/couchbase-index-manager && npm publish
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: cd packages/couchbase-index-manager-cli && npm publish
  on:
    tags: true
cache:
  directories:
  - node_modules
