name: beer_primary
is_primary: true
---
name: BeersByAbv
index_key:
- abv
condition: type = 'beer'
num_replica: 0
---
name: BeersByIbu
index_key:
- ibu
condition: type = 'beer'
num_replica: 0
---
name: DocsByType
index_key:
- type
---
name: BreweriesByAddress
index_key:
- distinct array p for p in address end
condition: type = 'brewery'
num_replica: 2
---
type: override # Overrides valus set previously for this index
name: BreweriesByAddress
num_replica: 0
# A post processing function can futher alter the definition
# "this" will be the index definition
post_process: |
  console.log(`Num replicas: ${this.num_replica}`);
---
type: nodeMap
map:
  node1: node1.cbindexmgr
  node2: node2.cbindexmgr
  node3: node3.cbindexmgr
---
name: sg_roleAccess_x1
index_key:
- (all (array (`op`.`name`) for `op` in object_pairs((((meta().`xattrs`).`_sync`).`role_access`)) end))
retain_deleted_xattr: false
---
name: oldIndex
lifecycle:
  drop: true
