name: beer_primary
is_primary: true
---
name: BeersByAbv
index_key:
- abv
condition: (`type` = 'beer')
num_replica: 0
---
name: BeersByIbu
index_key:
- ibu
condition: (`type` = 'beer')
num_replica: 0
---
name: BreweriesByAddress
index_key:
- (distinct (array `p` for `p` in `address` end))
condition: (`type` = 'brewery')
num_replica: 0
